### ISSUE TITLE
 It works in version 10?

### ISSUE THREAD

**Issue by rodrigodecosta** [sergiotocalini/zapgix#4]
I can not monitor the trigger item: 
PostgreSQL: Service was restarted (uptime = 00: 00: 00) 
and also to:
PostgreSQL: Cache hit ratio too low (0 %)

**Comment by sergiotocalini** [comment]
Hi @rodrigodecosta 
It should work, maybe there are some queries that need to be adapted but the main script should work. Actually, I'll introduce a new way to include different sql files for different versions.
Probably your problem is between the user and the connection to the database because the script is returning as a fallback always 0.
Best,
Sergio
